{
    "name": "City Tax",
    "summary": "Overview of all guest lines used for city tax reporting.",
    "version": "19.0.1.1.6",
    "category": "Hidden/Tools",
    "license": "OPL-1",
    "author": "mytime.click",
    "website": "https://mytime.click",
    "depends": [
        # "booking_engine", industry modules can't be added as dependencies.
        "partner_title",
        "partner_contact_personal_information_page",
        "partner_contact_birthdate",
        "sale_channel",
    ],
    "external_dependencies": {"python": ["requests", "playwright", "gender_guesser"]},
    "data": [
        "security/ir.model.access.csv",
        "data/ir_model_fields.xml",
        "data/ir_default.xml",
        "data/ir_sequence.xml",
        "views/menu_city_tax.xml",
        "views/guest_tax_message_views.xml",
        "views/x_guests_line_views.xml",
        "views/deskline_log_views.xml",
        "views/sale_order_views.xml",
        "views/res_partner_views.xml",
        "views/res_company_views.xml",
    ],
    "installable": True,
    "application": False,
}
