{
    "name": "Cash Journal Frontend",
    "summary": "Let registered users create cash journal transactions from a website page.",
    "version": "19.0.1.0.27",
    "category": "Accounting",
    "license": "OPL-1",
    "author": "mytime.click",
    "website": "https://mytime.click",
    "depends": [
        "account",
        "account_accountant",
        "account_analytic_distribution_manual",
        "account_analytic_tag",
        "account_statement_base",
        "analytic",
        "hr",
        "website",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/account_bank_statement_line_views.xml",
        "views/res_users_views.xml",
        "views/cash_journal_frontend_distribution_templates.xml",
        "views/cash_journal_frontend_camera_templates.xml",
        "views/cash_journal_frontend_templates.xml",
        "views/cash_journal_frontend_transaction_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "https://cdn.jsdelivr.net/npm/tom-select@2.6.2/dist/css/tom-select.css",
            "https://cdn.jsdelivr.net/npm/tom-select@2.6.2/dist/js/tom-select.complete.min.js",
            "cash_journal_frontend/static/src/css/cash_journal_frontend.css",
            "cash_journal_frontend/static/src/js/cash_analytic_search.js",
            "cash_journal_frontend/static/src/js/cash_camera.js",
        ],
    },
    "installable": True,
    "application": False,
}
