{
    "name": "Private WhatsApp",
    "summary": "Link a private WhatsApp account and send messages to contacts.",
    "version": "19.0.7.2.1",
    "category": "Productivity/Discuss",
    "license": "OPL-1",
    "author": "mytime.click",
    "website": "https://mytime.click",
    "depends": ["camping_base", "whatsapp"],
    "external_dependencies": {"python": ["neonize", "qrcode"]},
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "wizard/whatsapp_composer_views.xml",
        "wizard/whatsapp_send_message_wizard_views.xml",
        "wizard/whatsapp_contact_sync_wizard_views.xml",
        "views/res_company_views.xml",
        "views/res_partner_views.xml",
        "views/whatsapp_account_views.xml",
        "views/whatsapp_template_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "whatsapp_private/static/src/fields/live_qr/live_qr.js",
            "whatsapp_private/static/src/fields/live_qr/live_qr.xml",
            (
                "after",
                "whatsapp/static/src/core/common/thread_model_patch.js",
                "whatsapp_private/static/src/core/common/thread_model_patch.js",
            ),
        ],
    },
    "installable": True,
    "application": False,
}
