{
    "name": "Guest Registration",
    "summary": "Public link to let a customer complete address, contact and guest details.",
    "version": "19.0.1.0.0",
    "category": "Website",
    "license": "OPL-1",
    "author": "mytime.click",
    "website": "https://mytime.click",
    "depends": [
        "booking_engine",
        "camping_automation",
        "website",
        "mail",
        "id_detection",
        "base_location",
        "account",
        "city_tax",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/mail_template_data.xml",
        "wizard/guest_registration_link_wizard_views.xml",
        "wizard/guest_registration_wizard_views.xml",
        "wizard/guest_registration_guest_wizard_views.xml",
        "views/sale_order_views.xml",
        "views/guest_registration_templates.xml",
    ],
    "installable": True,
    "application": False,
}
