import base64
import io
import json
import logging
import re

import requests
from markupsafe import Markup, escape
from PIL import Image as PILImage
from PIL import ImageDraw, ImageFont

from odoo import Command, api, fields, models
from odoo.exceptions import UserError

from odoo.addons.ai.utils.llm_api_service import LLMApiService

from ._const import (
    FLOWER_ANNOTATION_COLORS,
    FLOWER_CALCULATOR_DETECTION_INSTRUCTIONS,
    FLOWER_CALCULATOR_GARDENER_SYSTEM_PROMPT,
    FLOWER_CALCULATOR_MODEL,
    FLOWER_CALCULATOR_STEMS_SYSTEM_PROMPT,
    FLOWER_CALCULATOR_SYSTEM_PROMPT,
    FLOWER_CALCULATOR_USER_PROMPT,
    FLOWER_COUNTER_MODE_INTERNAL,
    FLOWER_COUNTER_MODE_SELECTION,
    FLOWER_COUNTER_MODE_STEMS,
    FLOWER_DETECTION_CONFIDENCE_THRESHOLD,
    FLOWER_MODEL_PROVIDERS,
    FLOWER_MODEL_SELECTION,
    FLOWER_OPENROUTER_URL,
    FLOWER_PRODUCT_CATEGORY_COMPLETE_NAME,
    get_flower_calculator_schema,
)

_logger = logging.getLogger(__name__)

IMAGE_MAGIC_NUMBERS = {
    b"\xff\xd8\xff": "image/jpeg",
    b"\x89PNG\r\n\x1a\n": "image/png",
    b"GIF87a": "image/gif",
    b"GIF89a": "image/gif",
}


def _guess_image_mimetype(raw_bytes):
    for magic, mimetype in IMAGE_MAGIC_NUMBERS.items():
        if raw_bytes.startswith(magic):
            return mimetype
    return "image/jpeg"


_LEGEND_FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
_LEGEND_FONT_SIZE = 18
_LEGEND_ROW_HEIGHT = 28
_LEGEND_SWATCH_SIZE = 18
_LEGEND_PADDING = 10


def _get_legend_font():
    try:
        return ImageFont.truetype(_LEGEND_FONT_PATH, _LEGEND_FONT_SIZE)
    except OSError:
        return ImageFont.load_default()


_JSON_TOKEN_RE = re.compile(
    r'(?P<key>"(?:\\.|[^"\\])*")(?=\s*:)'
    r'|(?P<string>"(?:\\.|[^"\\])*")'
    r"|(?P<literal>\btrue\b|\bfalse\b|\bnull\b"
    r"|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)"
)

_JSON_HIGHLIGHT_COLORS = {
    "key": "#a626a4",
    "string": "#50a14f",
    "literal": "#986801",
}


def _highlight_json(formatted_json):
    def replace(match):
        kind = match.lastgroup
        escaped = escape(match.group(0))
        return Markup('<span style="color:{}">{}</span>').format(_JSON_HIGHLIGHT_COLORS[kind], escaped)

    # formatted_json is generated by json.dumps() from our own record data
    # (trusted), and every token value is escaped in replace() before
    # being wrapped in markup.
    highlighted = Markup(_JSON_TOKEN_RE.sub(replace, formatted_json))  # nosec B704
    return Markup('<pre style="overflow-x:auto; white-space:pre; margin:0;">{}</pre>').format(highlighted)


class SaleOrder(models.Model):
    _inherit = "sale.order"

    flower_image = fields.Image(string="Flower Photo", max_width=1920, max_height=1920)
    flower_counter = fields.Selection(
        FLOWER_COUNTER_MODE_SELECTION,
        default="default",
        required=True,
    )
    flower_model = fields.Selection(
        FLOWER_MODEL_SELECTION,
        default=FLOWER_CALCULATOR_MODEL,
        required=True,
    )
    flower_last_request_cost = fields.Float(
        string="Last Request Cost (USD)",
        digits=(16, 6),
        help="Cost reported by OpenRouter for the last analysis. Not available for OpenAI models.",
    )
    flower_last_request_tokens = fields.Integer(
        string="Last Request Tokens",
        help="Total tokens (prompt + completion + reasoning) reported by OpenRouter for the last "
        "analysis. Not available for OpenAI models.",
    )
    flower_annotate = fields.Boolean(
        string="Draw Flower Outlines",
        default=False,
        help="Ask ChatGPT to locate each flower and draw a colored outline around it in a new photo.",
    )
    flower_auto_complete_flow = fields.Boolean(
        string="Automatically Map and Add to Order",
        help=(
            "After analyzing the photo, create mappings for new flower names and add all detected "
            "flowers to the order. Unmatched flowers use the configured small or large fallback price."
        ),
    )
    flower_annotated_image = fields.Image(
        string="Annotated Flower Photo",
        max_width=1920,
        max_height=1920,
    )
    flower_analysis_json = fields.Json(string="Flower Analysis")
    flower_detected_ids = fields.One2many("flower.calculator.flower", "sale_order_id", string="Detected Flowers")
    flower_analysis_display = fields.Text(
        string="Flower Analysis (Formatted)",
        compute="_compute_flower_analysis_display",
    )
    flower_analysis_json_formatted = fields.Text(compute="_compute_flower_analysis_json_formatted")
    flower_analysis_json_html = fields.Html(compute="_compute_flower_analysis_json_html", sanitize=False)
    flower_total_quantity = fields.Integer(compute="_compute_flower_total_quantity")

    @api.depends("flower_analysis_json")
    def _compute_flower_total_quantity(self):
        for order in self:
            flowers = (order.flower_analysis_json or {}).get("flowers") or []
            order.flower_total_quantity = sum(flower.get("quantity") or 0 for flower in flowers)

    @api.depends("flower_analysis_json")
    def _compute_flower_analysis_display(self):
        for order in self:
            flowers = (order.flower_analysis_json or {}).get("flowers") or []
            order.flower_analysis_display = (
                "\n\n".join(order._format_flower_analysis_entry(flower) for flower in flowers) or False
            )

    @api.depends("flower_analysis_json")
    def _compute_flower_analysis_json_formatted(self):
        for order in self:
            if not order.flower_analysis_json:
                order.flower_analysis_json_formatted = False
                continue
            order.flower_analysis_json_formatted = json.dumps(
                order.flower_analysis_json, indent=2, ensure_ascii=False, sort_keys=True
            )

    @api.depends("flower_analysis_json_formatted")
    def _compute_flower_analysis_json_html(self):
        for order in self:
            order.flower_analysis_json_html = (
                _highlight_json(order.flower_analysis_json_formatted)
                if order.flower_analysis_json_formatted
                else False
            )

    def _format_flower_analysis_entry(self, flower):
        lines = [f"{flower.get('name') or '?'} — {flower.get('quantity') or 0}x ({flower.get('size') or '?'})"]
        botanical_parts = [
            part
            for part in (
                flower.get("genus"),
                flower.get("german_name"),
                flower.get("group_type"),
                flower.get("variety"),
                flower.get("color"),
            )
            if part
        ]
        if botanical_parts:
            lines.append("  " + " · ".join(botanical_parts))
        if flower.get("description"):
            lines.append(f"  {flower['description']}")
        reported_product_id = flower.get("product_id")
        if reported_product_id:
            match_line = self.env._("  Catalog match: #%(product_id)s")
            match_line = match_line % {"product_id": reported_product_id}
        else:
            match_line = self.env._("  No catalog match")
        lines.append(match_line)
        return "\n".join(lines)

    def _get_flower_product_domain(self):
        domain = [("sale_ok", "=", True)]
        category_id = self.env["product.category"].search(
            [("complete_name", "=", FLOWER_PRODUCT_CATEGORY_COMPLETE_NAME)],
            limit=1,
        )
        if category_id:
            domain.append(("categ_id", "child_of", category_id.id))
        return domain

    def _get_flower_catalog_products(self):
        return self.env["product.product"].search(self._get_flower_product_domain())

    def _get_flower_catalog_prompt(self, catalog_products):
        if not catalog_products:
            return False
        catalog_lines = [f"{product.id}: {product.display_name}" for product in catalog_products]
        catalog_prompt = self.env._("Our product catalog (database id: product name): %(catalog)s")
        return catalog_prompt % {"catalog": "; ".join(catalog_lines)}

    def _get_flower_analysis_system_prompts(self):
        if self.flower_counter == FLOWER_COUNTER_MODE_INTERNAL:
            system_prompts = [FLOWER_CALCULATOR_SYSTEM_PROMPT]
        elif self.flower_counter == FLOWER_COUNTER_MODE_STEMS:
            system_prompts = [FLOWER_CALCULATOR_STEMS_SYSTEM_PROMPT]
        else:
            return [FLOWER_CALCULATOR_GARDENER_SYSTEM_PROMPT]

        catalog_prompt = self._get_flower_catalog_prompt(self._get_flower_catalog_products())
        if catalog_prompt:
            system_prompts.append(catalog_prompt)
        return system_prompts

    def action_analyze_flower_image(self):
        self.ensure_one()
        if not self.flower_image:
            raise UserError(self.env._("Upload or take a photo of the flowers first."))
        raw_bytes = base64.b64decode(self.flower_image)
        image_bytes = raw_bytes
        pad_x = pad_y = 0
        square_side = None
        if self.flower_annotate:
            # Vision models are noticeably worse at placing bounding boxes on
            # tall/portrait photos - padding to a square canvas before
            # sending removes that aspect-ratio bias. The known offset is
            # then subtracted back out when converting detections to pixel
            # coordinates on the original (unpadded) photo.
            image_bytes, pad_x, pad_y, square_side = self._pad_image_to_square(raw_bytes)
        files = [
            {
                "mimetype": _guess_image_mimetype(image_bytes),
                "value": base64.b64encode(image_bytes).decode(),
            }
        ]
        system_prompts = self._get_flower_analysis_system_prompts()
        if self.flower_annotate:
            system_prompts.append(FLOWER_CALCULATOR_DETECTION_INSTRUCTIONS)
        schema = get_flower_calculator_schema(self.flower_annotate)
        provider = FLOWER_MODEL_PROVIDERS.get(self.flower_model, "openai")
        self.flower_last_request_cost = 0.0
        self.flower_last_request_tokens = 0
        if provider == "openrouter":
            responses = [
                self._request_openrouter_analysis(system_prompts, files[0], schema),
            ]
        else:
            responses = LLMApiService(self.env, provider=provider).request_llm(
                llm_model=self.flower_model,
                system_prompts=system_prompts,
                user_prompts=[FLOWER_CALCULATOR_USER_PROMPT],
                files=files,
                schema=schema,
                temperature=0,
            )
        if not responses:
            raise UserError(self.env._("ChatGPT did not return any data for this photo."))
        try:
            analysis = json.loads(responses[0])
        except (TypeError, ValueError) as error:
            message = self.env._("ChatGPT did not return valid JSON: %(error)s")
            message = message % {"error": error}
            raise UserError(message) from error
        self._validate_analysis_product_ids(analysis)
        self.flower_analysis_json = analysis
        self.flower_annotated_image = False
        self.flower_detected_ids = [Command.clear()] + [
            Command.create(self._prepare_detected_flower_vals(flower)) for flower in analysis.get("flowers") or []
        ]
        detections = analysis.get("detections") or []
        if self.flower_annotate and detections:
            self.flower_annotated_image = self._generate_flower_annotated_image(
                raw_bytes, detections, pad_x, pad_y, square_side
            )
        if self.flower_auto_complete_flow:
            self._sync_flower_mappings()
            return self.action_add_flowers_to_order_lines()
        return True

    def _validate_analysis_product_ids(self, analysis):
        """Discard model-produced IDs which were not in the supplied catalog."""
        if self.flower_counter not in (FLOWER_COUNTER_MODE_INTERNAL, FLOWER_COUNTER_MODE_STEMS):
            for flower in analysis.get("flowers") or []:
                flower["product_id"] = None
            return

        allowed_product_ids = set(self._get_flower_catalog_products().ids)
        for flower in analysis.get("flowers") or []:
            if flower.get("product_id") not in allowed_product_ids:
                flower["product_id"] = None

    def _request_openrouter_analysis(self, system_prompts, image_file, schema):
        api_key = self.env["ir.config_parameter"].sudo().get_param("flower_calculator.openrouter_api_key")
        if not api_key:
            raise UserError(self.env._("No OpenRouter API key is configured. Add one in Settings."))
        body = {
            "model": self.flower_model,
            "max_tokens": 32000,
            # Gemini's "thinking" can otherwise consume the entire max_tokens
            # budget on internal reasoning, leaving nothing for the actual
            # JSON answer (content comes back null). Capping it low leaves
            # the budget for the visible output instead.
            "reasoning": {"max_tokens": 1024},
            "response_format": {
                "type": "json_schema",
                "json_schema": {"name": "flower_calculator", "schema": schema, "strict": True},
            },
            "messages": [
                {"role": "system", "content": "\n".join(system_prompts)},
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": FLOWER_CALCULATOR_USER_PROMPT},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:{image_file['mimetype']};base64,{image_file['value']}",
                            },
                        },
                    ],
                },
            ],
        }
        response = requests.post(
            FLOWER_OPENROUTER_URL,
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            json=body,
            timeout=60,
        )
        try:
            response.raise_for_status()
        except requests.exceptions.RequestException as error:
            try:
                detail = response.json().get("error", {}).get("message") or response.text
            except ValueError:
                detail = response.text
            message = self.env._("OpenRouter request failed: %(error)s")
            message = message % {"error": detail}
            raise UserError(message) from error
        data = response.json()
        usage = data.get("usage") or {}
        self.flower_last_request_cost = usage.get("cost") or 0.0
        self.flower_last_request_tokens = usage.get("total_tokens") or 0
        content = data["choices"][0]["message"]["content"]
        if not content:
            finish_reason = data["choices"][0].get("finish_reason")
            message = self.env._(
                "OpenRouter returned no content (finish_reason: %(finish_reason)s). The model likely "
                "used its entire token budget on internal reasoning before writing an answer. Try again, "
                "or use a different model."
            )
            message = message % {"finish_reason": finish_reason}
            raise UserError(message)
        return content

    def _pad_image_to_square(self, raw_bytes):
        image = PILImage.open(io.BytesIO(raw_bytes)).convert("RGB")
        width, height = image.size
        side = max(width, height)
        pad_x = (side - width) // 2
        pad_y = (side - height) // 2
        canvas = PILImage.new("RGB", (side, side), (128, 128, 128))
        canvas.paste(image, (pad_x, pad_y))
        buffer = io.BytesIO()
        canvas.save(buffer, format="JPEG", quality=90)
        return buffer.getvalue(), pad_x, pad_y, side

    def _prepare_detected_flower_vals(self, flower):
        reported_product_id = flower.get("product_id")
        product_id = self.env["product.product"]
        if reported_product_id:
            product_id = product_id.browse(reported_product_id).exists()
        return {
            "name": (flower.get("name") or "").strip(),
            "quantity": flower.get("quantity") or 0,
            "size": flower.get("size") or False,
            "product_id": product_id.id,
            "description": flower.get("description"),
            "genus": flower.get("genus"),
            "german_name": flower.get("german_name"),
            "group_type": flower.get("group_type"),
            "variety": flower.get("variety"),
            "color": flower.get("color"),
        }

    def _generate_flower_annotated_image(self, raw_bytes, detections, pad_x, pad_y, square_side):
        image = PILImage.open(io.BytesIO(raw_bytes)).convert("RGB")
        draw = ImageDraw.Draw(image)
        width, height = image.size
        color_by_name = {}
        for detection in detections:
            confidence = detection.get("confidence")
            if confidence is not None and confidence < FLOWER_DETECTION_CONFIDENCE_THRESHOLD:
                continue
            name = detection.get("name") or "?"
            if name not in color_by_name:
                color_by_name[name] = FLOWER_ANNOTATION_COLORS[len(color_by_name) % len(FLOWER_ANNOTATION_COLORS)]
            box = self._get_detection_pixel_box(detection, pad_x, pad_y, square_side, width, height)
            if box:
                draw.rectangle(box, outline=color_by_name[name], width=3)
        canvas = self._add_flower_legend(image, color_by_name)
        buffer = io.BytesIO()
        canvas.save(buffer, format="JPEG", quality=90)
        return base64.b64encode(buffer.getvalue())

    def _add_flower_legend(self, image, color_by_name):
        if not color_by_name:
            return image
        width, height = image.size
        legend_height = _LEGEND_PADDING * 2 + len(color_by_name) * _LEGEND_ROW_HEIGHT
        canvas = PILImage.new("RGB", (width, height + legend_height), (255, 255, 255))
        canvas.paste(image, (0, 0))
        draw = ImageDraw.Draw(canvas)
        font = _get_legend_font()
        y = height + _LEGEND_PADDING
        for name, color in color_by_name.items():
            draw.rectangle(
                (_LEGEND_PADDING, y, _LEGEND_PADDING + _LEGEND_SWATCH_SIZE, y + _LEGEND_SWATCH_SIZE),
                fill=color,
                outline=(0, 0, 0),
            )
            draw.text((_LEGEND_PADDING * 2 + _LEGEND_SWATCH_SIZE, y), name, fill=(0, 0, 0), font=font)
            y += _LEGEND_ROW_HEIGHT
        return canvas

    def _get_detection_pixel_box(self, detection, pad_x, pad_y, square_side, width, height):
        try:
            x_min = max(0.0, min(1.0, float(detection["x_min"])))
            y_min = max(0.0, min(1.0, float(detection["y_min"])))
            x_max = max(0.0, min(1.0, float(detection["x_max"])))
            y_max = max(0.0, min(1.0, float(detection["y_max"])))
        except (KeyError, TypeError, ValueError):
            return None
        if x_max <= x_min or y_max <= y_min:
            return None
        side = square_side or max(width, height)
        box = (
            max(0.0, min(width, x_min * side - pad_x)),
            max(0.0, min(height, y_min * side - pad_y)),
            max(0.0, min(width, x_max * side - pad_x)),
            max(0.0, min(height, y_max * side - pad_y)),
        )
        if box[2] <= box[0] or box[3] <= box[1]:
            return None
        return box

    def action_add_flowers_to_order_lines(self):
        self.ensure_one()
        flowers = (self.flower_analysis_json or {}).get("flowers") or []
        if not flowers:
            raise UserError(self.env._("Analyze a flower photo first."))
        flower_names = [(flower.get("name") or "").strip() for flower in flowers]
        mapping_by_name = {
            mapping.chatgpt_name: mapping.product_id
            for mapping in self.env["flower.calculator.mapping"].search([("chatgpt_name", "in", flower_names)])
        }
        command_list = []
        fallback_names = []
        for flower in flowers:
            flower_name = (flower.get("name") or "").strip()
            quantity = flower.get("quantity") or 0
            product_id = mapping_by_name.get(flower_name) or self.env["product.product"]
            if not product_id:
                reported_product_id = flower.get("product_id")
                if reported_product_id:
                    product_id = self.env["product.product"].browse(reported_product_id).exists()
            if not product_id:
                product_id = self.env["product.product"].search(
                    [("name", "ilike", flower_name), *self._get_flower_product_domain()],
                    limit=1,
                )
            if product_id:
                command_list.append(
                    Command.create(
                        {
                            "product_id": product_id.id,
                            "product_uom_qty": quantity,
                            "flower_calculator_generated": True,
                        }
                    )
                )
                continue
            fallback_names.append(flower_name)
            is_large = flower.get("size") == "large"
            price_unit = self.company_id.default_flower_large if is_large else self.company_id.default_flower_small
            command_list.append(
                Command.create(
                    {
                        "name": flower_name,
                        "product_uom_qty": quantity,
                        "price_unit": price_unit,
                        "flower_calculator_generated": True,
                    }
                )
            )
        generated_lines = self.order_line.filtered("flower_calculator_generated")
        self.order_line = [Command.delete(line.id) for line in generated_lines] + command_list
        if fallback_names:
            _logger.info("Flower calculator: used default price for %s", fallback_names)
            message = self.env._("Used the default price for: %(names)s")
            message = message % {"names": ", ".join(fallback_names)}
            return {
                "type": "ir.actions.client",
                "tag": "display_notification",
                "params": {
                    "title": self.env._("Some flowers used a default price"),
                    "message": message,
                    "type": "info",
                    "sticky": False,
                },
            }
        return True

    def _sync_flower_mappings(self):
        self.ensure_one()
        flowers = (self.flower_analysis_json or {}).get("flowers") or []
        flower_by_name = {
            (flower.get("name") or "").strip(): flower for flower in flowers if (flower.get("name") or "").strip()
        }
        existing_names = set(
            self.env["flower.calculator.mapping"]
            .search([("chatgpt_name", "in", list(flower_by_name))])
            .mapped("chatgpt_name")
        )
        created_mappings = self.env["flower.calculator.mapping"]
        catalog_products = self._get_flower_catalog_products()
        for flower_name in sorted(set(flower_by_name) - existing_names):
            flower = flower_by_name[flower_name]
            product = self.env["product.product"]
            reported_product_id = flower.get("product_id")
            if reported_product_id:
                product = catalog_products.filtered(
                    lambda catalog_product, product_id=reported_product_id: catalog_product.id == product_id
                )[:1]
            if not product:
                product = self.env["product.product"].search(
                    [("name", "ilike", flower_name), *self._get_flower_product_domain()],
                    limit=1,
                )
            created_mappings |= self.env["flower.calculator.mapping"].create(
                {
                    "chatgpt_name": flower_name,
                    "german_name": flower.get("german_name"),
                    "variety": flower.get("variety"),
                    "product_id": product.id,
                }
            )
        return created_mappings


class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    flower_calculator_generated = fields.Boolean(copy=False)
