{
    "name": "Camping Additional Fields Base",
    "summary": "Base module for additional camping-specific fields on products.",
    "version": "19.0.1.1.0",
    "category": "Sales/Rental",
    "license": "OPL-1",
    "author": "mytime.click",
    "website": "https://mytime.click",
    "depends": [
        "camping_base",
        "odoo_whatsapp_integration",
        "product",
        "sale",
        "sale_brand",
        "sale_channel",
        "sale_renting",
        "website_sale",
        "booking_engine",
        "planning",
    ],
    "data": [
        "data/ir_cron.xml",
        "data/ir_model_fields.xml",
        "views/booking_engine_menu_views.xml",
        "views/planning_role_menu_views.xml",
        "views/planning_slot_views.xml",
        "views/product_template_views.xml",
        "views/res_company_views.xml",
        "views/sale_channel_views.xml",
        "views/sale_order_views.xml",
    ],
    "assets": {
        "web.assets_backend_lazy": [
            "camping_additional_fields_base/static/src/views/planning_gantt_renderer.js",
        ],
    },
    "installable": True,
    "application": False,
}
