{
    "name": "Mail to Booking",
    "summary": "Create camping rental bookings from incoming emails using DeepSeek.",
    "version": "19.0.1.0.0",
    "category": "Sales/Rental",
    "license": "OPL-1",
    "author": "mytime.click",
    "website": "https://mytime.click",
    "depends": [
        "mail",
        "sale_renting",
        "sale_channel",
        "booking_engine",
    ],
    "external_dependencies": {"python": ["requests", "pdfminer"]},
    "data": [
        "security/ir.model.access.csv",
        "views/mail_to_booking_views.xml",
        "views/mail_to_booking_product_mapping_views.xml",
        "views/mail_to_booking_subject_blocklist_views.xml",
        "views/fetchmail_server_views.xml",
        "views/res_company_views.xml",
        "views/sale_channel_views.xml",
        "wizard/mail_to_booking_product_mapping_wizard_views.xml",
        "wizard/mail_to_booking_not_booking_wizard_views.xml",
    ],
    "installable": True,
    "application": False,
}
