{
    "name": "Mytime LG Application",
    "summary": "Bundles all mytime.click modules for this instance into one app.",
    "version": "19.0.1.0.0",
    "category": "Sales/Rental",
    "license": "OPL-1",
    "author": "mytime.click",
    "website": "https://mytime.click",
    "depends": [
        "camping_automation",
        "camping_communication",
        "cash_journal_frontend",
        "cash_journal_frontend_development",
        "city_tax",
        "city_tax_loading",
        "city_tax_nw",
        "insert_from_mail",
        "mail_global_inbox",
        "mail_to_booking",
        "mail_to_booking_settings",
        "mytime_pitchup_sync",
    ],
    "installable": True,
    "application": True,
}
